site_name: WIPAC Meetings
copyright: Copyright &copy; 2021
nav:
  - Home: index.md
  - 'Virtual Spring 2021':
    - virtualspring2021/home.md
    - virtualspring2021/registration.md
    - virtualspring2021/indico.md
    - virtualspring2021/schedule.md
    - virtualspring2021/codeofconduct.md
    - virtualspring2021/contactus.md
theme:
  name: material
  custom_dir: overrides
  favicon: images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.caret
  - attr_list
  - pymdownx.keys
  - md_in_html
  - smarty
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
